#!/bin/sh

DB="/data/pdns/pdns.sqlite3"
LOCALCONF="/data/pdns.local.conf"

if ! test -e "$DB"; then
    mkdir "$(dirname "$DB")"
    cp /var/lib/powerdns/pdns.sqlite3 "$DB"
    chown pdns:pdns "$(dirname "$DB")" "$DB"
fi

if ! test -e "$LOCALCONF"; then
    cp /etc/powerdns/pdns.local.conf.template "$LOCALCONF"
    echo "api-key=$(openssl rand -hex 32)" >> "$LOCALCONF"
    chown pdns:pdns "$LOCALCONF"
fi

exec pdns_server
