#!/bin/bash
set -eux

SERVER="$1"
SCRIPT="$2"

TMPPATH="/tmp/$RANDOM$RANDOM$RANDOM"
ssh "$SERVER" mkdir -p "$TMPPATH"
rsync -v "$SCRIPT" "$SERVER":"$TMPPATH/debos.yaml"
ssh "$SERVER" cd "$TMPPATH" "&&" "~/go/bin/debos" "$TMPPATH/debos.yaml"
rsync -av "$SERVER":"$TMPPATH/" "."
ssh "$SERVER" rm -r "$TMPPATH/"
