#!/bin/sh -eu

printf "$(printf '\\%o' $(printf '0x%s ' $3))" | dd of="$1" conv=notrunc bs=1 seek="$(tr '\0\12' '\32' < "$1" | grep -Fabo "$(printf "$(printf '\\%o' $(printf '0x%s ' $2))" | tr '\0\12' '\32')" | cut -d: -f1)"
