#!/bin/sh -xeu

shutdown() {
  trap - EXIT
  echo "$0: Shutting down" >&2
  ps -Af >&2
  while pkill -eP "$$" >&2; do sleep 1; done
  exit
}

trap shutdown TERM INT HUP EXIT

for s in /etc/my_init.d/*; do "$s" & wait; done
runsvdir -P /etc/service & wait
