defaultEntryPoints = ["https", "http"]

[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[file]
[backends.invalid]
[frontends.default]
backend = "invalid"
rule = "HostRegexp:{a:.*}"
priority = -1

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "invalid.invalid"
exposedByDefault = false

[acme]
# email = "invalid@invalid.invalid"
storage = "/acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.tlsChallenge]
