#!/bin/sh
set -eu

HERE="$(cd "$(dirname -- "$0")"; pwd)"
# . "$HERE"/dns-env

DOMAIN="$1"

CERTFILE="/etc/os-release"
KEYFILE="/etc/os-release"

cat << EOF
#cloud-config
write_files:
- encoding: b64
  owner: root:root
  path: /etc/nghttpx/server.key
  permissions: "0644"
  content: $(base64 --wrap=0 "$KEYFILE")
- encoding: b64
  owner: root:root
  path: /etc/nghttpx/server.crt
  permissions: "0644"
  content: $(base64 --wrap=0 "$CERTFILE")
- encoding: b64
  owner: root:root
  path: /domain
  permissions: "0644"
  content: $(printf "%s" "$DOMAIN" | base64 --wrap=0)
password: eaas
chpasswd: {expire: False}
EOF
