#!/bin/sh
set -eu

HERE="$(cd "$(dirname -- "$0")"; pwd)"
# . "$HERE"/dns-env

DOMAIN="$1"

BASEDOMAIN="${DOMAIN#*.}"
CERTDOMAIN="*.$BASEDOMAIN"

#acme.sh --test --issue -d "$CERTDOMAIN" >&2

ACMESHDIR="/data/acme.sh/"
CERTFILE="$ACMESHDIR/$CERTDOMAIN/fullchain.cer"
KEYFILE="$ACMESHDIR/$CERTDOMAIN/$CERTDOMAIN.key"

CERTFILE="/etc/os-release"
KEYFILE="/etc/os-release"

cat << EOF
#cloud-config
write_files:
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /etc/nghttpx/server.key
  content: $(base64 --wrap=0 "$KEYFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /etc/nghttpx/server.crt
  content: $(base64 --wrap=0 "$CERTFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /domain
  content: $(printf "%s\n" "$DOMAIN" | base64 --wrap=0)
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /certdomain
  content: $(printf "%s\n" "$CERTDOMAIN" | base64 --wrap=0)
#password: eaas
#chpasswd: {expire: false}
EOF
